# Generated by Django 5.2.3 on 2025-06-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_skill_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={},
        ),
        migrations.RemoveField(
            model_name='skill',
            name='order',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='proficiency',
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(choices=[('Python', 'Python'), ('Java', 'Java'), ('JavaScript', 'JavaScript'), ('TypeScript', 'TypeScript'), ('C', 'C'), ('C++', 'C++'), ('C#', 'C#'), ('Go', 'Go'), ('Rust', 'Rust'), ('Ruby', 'Ruby'), ('PHP', 'PHP'), ('Swift', 'Swift'), ('Kotlin', 'Kotlin'), ('Scala', 'Scala'), ('Dart', 'Dart'), ('Objective-C', 'Objective-C'), ('Perl', 'Perl'), ('R', 'R'), ('MATLAB', 'MATLAB'), ('SQL', 'SQL'), ('HTML', 'HTML'), ('CSS', 'CSS'), ('React', 'React'), ('Vue.js', 'Vue.js'), ('Angular', 'Angular'), ('Django', 'Django'), ('Flask', 'Flask'), ('Spring', 'Spring'), ('Express.js', 'Express.js'), ('Laravel', 'Laravel'), ('.NET', '.NET')], max_length=100, unique=True),
        ),
    ]
