# Generated by Django 5.2.3 on 2025-06-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_skill_options_remove_skill_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='project',
            name='date_created',
        ),
        migrations.AlterField(
            model_name='project',
            name='live_demo_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(choices=[('Python', 'Python'), ('Java', 'Java'), ('JavaScript', 'JavaScript'), ('TypeScript', 'TypeScript'), ('C', 'C'), ('C++', 'C++'), ('C#', 'C#'), ('Go', 'Go'), ('Rust', 'Rust'), ('Ruby', 'Ruby'), ('PHP', 'PHP'), ('Swift', 'Swift'), ('Kotlin', 'Kotlin'), ('Scala', 'Scala'), ('Perl', 'Perl'), ('Dart', 'Dart'), ('Objective-C', 'Objective-C'), ('MATLAB', 'MATLAB'), ('R', 'R'), ('SQL', 'SQL'), ('HTML', 'HTML'), ('CSS', 'CSS'), ('React', 'React'), ('Vue.js', 'Vue.js'), ('Angular', 'Angular'), ('Django', 'Django'), ('Flask', 'Flask'), ('Spring', 'Spring'), ('Express.js', 'Express.js'), ('Laravel', 'Laravel'), ('.NET', '.NET'), ('Node.js', 'Node.js')], max_length=100, unique=True),
        ),
    ]
