# Generated by Django 5.2.3 on 2025-06-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_skill_is_custom_alter_skill_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(help_text='Choose from the list or enter a new skill.', max_length=100, unique=True),
        ),
    ]
