# Generated by Django 5.2.3 on 2025-06-29 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_delete_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='technologies',
        ),
    ]
