# Generated by Django 5.2.3 on 2025-06-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_project_custom_skill_project_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('Python', 'Python'), ('Java', 'Java'), ('JavaScript', 'JavaScript'), ('TypeScript', 'TypeScript'), ('C', 'C'), ('C++', 'C++'), ('C#', 'C#'), ('Go', 'Go'), ('Rust', 'Rust'), ('Ruby', 'Ruby'), ('PHP', 'PHP'), ('Swift', 'Swift'), ('Kotlin', 'Kotlin'), ('Scala', 'Scala'), ('Dart', 'Dart'), ('Objective-C', 'Objective-C'), ('Perl', 'Perl'), ('R', 'R'), ('MATLAB', 'MATLAB'), ('SQL', 'SQL'), ('HTML', 'HTML'), ('CSS', 'CSS'), ('React', 'React'), ('Vue.js', 'Vue.js'), ('Angular', 'Angular'), ('Django', 'Django'), ('Flask', 'Flask'), ('Spring', 'Spring'), ('Express.js', 'Express.js'), ('Laravel', 'Laravel'), ('.NET', '.NET'), ('Node.js', 'Node.js')], max_length=100)),
                ('custom_name', models.CharField(blank=True, help_text='If not in the list, enter a custom skill or framework.', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='custom_skill',
        ),
        migrations.RemoveField(
            model_name='project',
            name='skill',
        ),
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='projects', to='portfolio.skill'),
        ),
    ]
