# Generated by Django 5.2.3 on 2025-06-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_skill_remove_project_custom_skill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='is_displayed',
            field=models.BooleanField(default=False, help_text='Whether this skill should be displayed on the UI'),
        ),
    ]
