# Generated by Django 5.2.3 on 2025-06-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_skill_is_displayed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='is_displayed',
        ),
        migrations.AddField(
            model_name='overview',
            name='about_me',
            field=models.TextField(blank=True, help_text='About me section content displayed on homepage'),
        ),
    ]
