# Generated by Django 5.2.3 on 2025-06-29 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_aboutme_remove_overview_about_me'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutMe',
        ),
    ]
