# Generated by Django 5.2.3 on 2025-06-30 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_delete_aboutme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
