# Generated by Django 5.2.3 on 2025-06-30 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0026_aboutme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutMe',
        ),
    ]
