# Generated by Django 5.2.3 on 2025-06-30 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0028_aboutme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutMe',
        ),
    ]
